name: ecommerce_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0' # Menggunakan rentang SDK yang lebih stabil

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  intl: ^0.19.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # Versi yang lebih umum

flutter:
  uses-material-design: true

  # Aset folder untuk font
  assets:
    - assets/fonts/

  # Deklarasi Font
  fonts:
    - family: Merriweather
      fonts:
        # File untuk gaya normal (tegak)
        - asset: assets/fonts/Merriweather-Regular.ttf

        # File untuk gaya miring (italic)
        - asset: assets/fonts/Merriweather-Italic.ttf
          style: italic